### ISSUE TITLE
(feature request) being able to use bicubic on more than just the light Maps

### ISSUE THREAD

**Issue by simsora13** [z3y/ShaderGraph#1]
would it be nice to be able to use bicubic filtering on more than just light Maps as it can make low-res textures look not as pixelated  so it could potentially vram

**Comment by simsora13** [comment]
![VRChat_2023-12-08_16-55-15 094_1920x1080](https://github.com/z3y/ShaderGraph/assets/20879116/990480d9-a828-490e-b73a-3ab0fb6613da)

**Comment by z3y** [comment]
The reason why the toggle exists only for lightmaps is because you have no control over sampling them in the graph. For your own textures you can use custom nodes to make your own sampling function so this is already possible.
I wouldnt use it on textures like this though, it makes looking at them uncomfortable and blurry.
